services:
  ### Postgres database for loan application
  db-loan:
    image: mysql:8.0.33
    container_name: db-loan
    environment:
      MYSQL_DATABASE: ms-loan
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - "3309:3306"
    expose:
      - 3309

  ### MySQL database for book application
  db-book:
    image: mysql:8.0.33
    container_name: db-book
    environment:
      MYSQL_DATABASE: ms-book
      MYSQL_ROOT_PASSWORD: admin  # Contraseña para el usuario root
    ports:
      - "3306:3306"
    expose:
      - 3306


  ### MySQL database for user application
  db-customer:
    image: mysql:8.0.33
    container_name: db-customer
    environment:
      MYSQL_DATABASE: ms-customer
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - "3308:3306"
    expose:
      - 3308



